### ISSUE TITLE
Tournament Games in get_team_schedule()

### ISSUE THREAD

**Issue by ghost** [JackLich10/gamezoneR#1]
It doesn't appear that the function retrieves games from the NCAA Tournament. Is that a limitation in the API?

**Comment by JackLich10** [comment]
Yes, unfortunately I am not able to get the API to request postseason games in previous seasons for team schedules. I'd recommend using `get_master_schedule(date = "2019-03-21", ranked = T)` for example if you want tournament games for a specific date.
